
name: Kaggle Model 3

conda_env: models/kagglemodel3/conda_env.yaml

entry_points:
  train:
    parameters:
      repo: kaggle
      config: models/kaggle_model3/config.json
    command: "python src/models/kaggle_model3.py train -repo {repo} -config "
  validate:
    parameters:
      repo: kaggle
      config: models/kaggle_model3/config.json
    command: "python src/models/kaggle_model3.py validate -repo {repo}"
