from . import utils as utils

def ratio(s1, s2): ...
def partial_ratio(s1, s2): ...
def token_sort_ratio(s1, s2, force_ascii: bool = ..., full_process: bool = ...): ...
def partial_token_sort_ratio(
    s1, s2, force_ascii: bool = ..., full_process: bool = ...
): ...
def token_set_ratio(s1, s2, force_ascii: bool = ..., full_process: bool = ...): ...
def partial_token_set_ratio(
    s1, s2, force_ascii: bool = ..., full_process: bool = ...
): ...
def QRatio(s1, s2, force_ascii: bool = ..., full_process: bool = ...): ...
def UQRatio(s1, s2, full_process: bool = ...): ...
def WRatio(s1, s2, force_ascii: bool = ..., full_process: bool = ...): ...
def UWRatio(s1, s2, full_process: bool = ...): ...
