from . import fuzz as fuzz, utils as utils
from _typeshed import Incomplete
from collections.abc import Generator

default_scorer: Incomplete
default_processor = utils.full_process

def extractWithoutOrder(
    query, choices, processor=..., scorer=..., score_cutoff: int = ...
) -> Generator[Incomplete, None, Incomplete]: ...
def extract(query, choices, processor=..., scorer=..., limit: int = ...): ...
def extractBests(
    query, choices, processor=..., scorer=..., score_cutoff: int = ..., limit: int = ...
): ...
def extractOne(query, choices, processor=..., scorer=..., score_cutoff: int = ...): ...
def dedupe(contains_dupes, threshold: int = ..., scorer=...): ...
