from Levenshtein import *
from _typeshed import Incomplete

class StringMatcher:
    def __init__(
        self, isjunk: Incomplete | None = ..., seq1: str = ..., seq2: str = ...
    ) -> None: ...
    def set_seqs(self, seq1, seq2) -> None: ...
    def set_seq1(self, seq1) -> None: ...
    def set_seq2(self, seq2) -> None: ...
    def get_opcodes(self): ...
    def get_editops(self): ...
    def get_matching_blocks(self): ...
    def ratio(self): ...
    def quick_ratio(self): ...
    def real_quick_ratio(self): ...
    def distance(self): ...
