from _typeshed import Incomplete
from thefuzz.string_processing import StringProcessor as StringProcessor

PY3: Incomplete

def validate_string(s): ...
def check_for_equivalence(func): ...
def check_for_none(func): ...
def check_empty_string(func): ...

bad_chars: Incomplete
translation_table: Incomplete
unicode = str

def asciionly(s): ...
def asciidammit(s): ...
def make_type_consistent(s1, s2): ...
def full_process(s, force_ascii: bool = ...): ...
def intr(n): ...
